/* Auto-generated by tools/gen_build_magic.py - do not hand-edit. */
#ifndef BUILD_MAGIC_H
#define BUILD_MAGIC_H

#define APP_BUILD_MAGIC 0xD9A0F1F1U
#define APP_BUILD_MAGIC_STR "0xD9A0F1F1"
#define APP_BUILD_MAGIC_TIME "2026-08-20 16:26:27 CEST"

#endif /* BUILD_MAGIC_H */
