#!/usr/bin/env python3
"""Generate include/build_magic.h with a fresh 32-bit magic value each run.

Run automatically by the Makefile before every build. The same value is printed
by the App on UART ([build-magic] ...) and by tools/flash_app.sh after flash,
so a log can be matched to the exact binary that was programmed.

    python tools/gen_build_magic.py
"""
import pathlib
import secrets
from datetime import datetime
from zoneinfo import ZoneInfo

now = datetime.now(ZoneInfo("Europe/Madrid"))
magic = secrets.randbelow(0x100000000)
magic_hex = f"0x{magic:08X}"
stamp = now.strftime("%Y-%m-%d %H:%M:%S %Z")

out_path = pathlib.Path(__file__).resolve().parent.parent / "include" / "build_magic.h"
out_path.write_text(
    "/* Auto-generated by tools/gen_build_magic.py - do not hand-edit. */\n"
    "#ifndef BUILD_MAGIC_H\n"
    "#define BUILD_MAGIC_H\n\n"
    f"#define APP_BUILD_MAGIC {magic_hex}U\n"
    f'#define APP_BUILD_MAGIC_STR "{magic_hex}"\n'
    f'#define APP_BUILD_MAGIC_TIME "{stamp}"\n\n'
    "#endif /* BUILD_MAGIC_H */\n",
    newline="\n",
)
print(f"Wrote {out_path} : APP_BUILD_MAGIC = {magic_hex} ({stamp})")
